version: '2'

services:
  postgres:
    image: 'postgres:10.0-alpine'
    environment:
      POSTGRES_USER: $USER
    ports:
      - '5442:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  website:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '3010:3010'
    volumes:
      - '.:/app'
    env_file:
      - '.env'

networks:
  default:
    external:
      name: turing-network
volumes:
  postgres:
