default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_FOR_DOCKER'].present? ? 'postgres' : 'localhost' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['DATABASE_FOR_DOCKER'].present? ? 'postgres' : ENV['USER'] %>

development:
  <<: *default
  database: census_development

test:
  <<: *default
  database: census_test

production:
  <<: *default
  database: census_production
  username: census
  password: <%= ENV['CENSUS_DATABASE_PASSWORD'] %>
