# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e00a3f09f602f74cb64ed7daead6cf63bdaabb9aa6247443bbcb88be36f3e363443c3e1c448809e714dbd8c5626f2c9f8da3cbc244a8ae3ce1f7adddb0a1f88b
  api_auth_secret: <%= ENV.fetch("API_AUTH_SECRET", "no-api-secret-set") %>
  enroll_graphql_endpoint: <%= ENV.fetch("ENROLL_GRAPHQL_ENDPOINT", "http://localhost:3001/graphql") %>

test:
  secret_key_base: ac1e649fcb1f5e6ca0afbc18a83a1851ec5e747f43ad29023e9e53120e069e879b7daaf8f4577e775c730a0a7665b0f30c77dd4505ba12bd8cf0432aeb641a05
  api_auth_secret: <%= ENV.fetch("API_AUTH_SECRET", "no-api-secret-set") %>
  enroll_graphql_endpoint: <%= ENV.fetch("ENROLL_GRAPHQL_ENDPOINT", "http://localhost:3001/graphql") %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_auth_secret: <%= ENV.fetch("API_AUTH_SECRET", "no-api-secret-set") %>
  enroll_graphql_endpoint: <%= ENV.fetch("ENROLL_GRAPHQL_ENDPOINT", "http://localhost:3001/graphql") %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_auth_secret: <%= ENV.fetch("API_AUTH_SECRET", "no-api-secret-set") %>
  enroll_graphql_endpoint: <%= ENV.fetch("ENROLL_GRAPHQL_ENDPOINT", "http://localhost:3001/graphql") %>
