development:
  secret_key_base: e00a3f09f602f74cb64ed7daead6cf63bdaabb9aa6247443bbcb88be36f3e363443c3e1c448809e714dbd8c5626f2c9f8da3cbc244a8ae3ce1f7adddb0a1f88b
  api_auth_secret: <%= ENV.fetch("API_AUTH_SECRET", "no-api-secret-set") %>
  enroll_graphql_endpoint: <%= ENV.fetch("ENROLL_GRAPHQL_ENDPOINT", "http://localhost:3001/graphql") %>
  require_ssl_redirect_uri: <%= ENV.fetch('REQUIRE_SSL_REDIRECT_URI', 'false') == 'true' %>

test:
  secret_key_base: ac1e649fcb1f5e6ca0afbc18a83a1851ec5e747f43ad29023e9e53120e069e879b7daaf8f4577e775c730a0a7665b0f30c77dd4505ba12bd8cf0432aeb641a05
  api_auth_secret: <%= ENV.fetch("API_AUTH_SECRET", "no-api-secret-set") %>
  enroll_graphql_endpoint: <%= ENV.fetch("ENROLL_GRAPHQL_ENDPOINT", "http://localhost:3001/graphql") %>
  require_ssl_redirect_uri: <%= ENV.fetch('REQUIRE_SSL_REDIRECT_URI', 'false') == 'true' %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_auth_secret: <%= ENV.fetch("API_AUTH_SECRET", "no-api-secret-set") %>
  enroll_graphql_endpoint: <%= ENV.fetch("ENROLL_GRAPHQL_ENDPOINT", "http://localhost:3001/graphql") %>
  require_ssl_redirect_uri: <%= ENV.fetch('REQUIRE_SSL_REDIRECT_URI', 'false') == 'true' %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_auth_secret: <%= ENV.fetch("API_AUTH_SECRET", "no-api-secret-set") %>
  enroll_graphql_endpoint: <%= ENV.fetch("ENROLL_GRAPHQL_ENDPOINT", "http://localhost:3001/graphql") %>
  require_ssl_redirect_uri: <%= ENV.fetch('REQUIRE_SSL_REDIRECT_URI', 'true') == 'true' %>
